### ISSUE TITLE
method_missing to dynamically generate #get

### ISSUE THREAD

**Issue by philipqnguyen** [procore/ruby-sdk#9]
Just an idea, but what does everyone think about utilizing Ruby's method_missing feature to dynamically generate methods that essentially calls `client.get('resource')` underneath?

For example:

`client.companies` => `client.get('companies')`
`client.me` => `client.get('me')`
`client.non_existent` => `client.get('non_existent') `

**Comment by PatKoperwas** [comment]
Originally, I was experimenting with generating methods from the Swagger docs. But due to the way the V2 API is designed, the way the methods came out was pretty ugly. For stuff like `client.me`, that API feels great and looks nice. 

Where it gets gross is when you start adding required and optional path parameters. How would you do something like: `/vapid/commitments/{commitment_id}/draw_requests`
https://developers.procore.com/reference/draw-requests#list-draw-requests-for-commitment

Starts getting awkward:

Because you can't just replace `/` in a url with an `underscore`, because some resources have an underscore in the name
```ruby
# This:
client.vapid_commitments_5_draw_requests(project_id: 5)

# Replacing _ with / results in an incorrect URL
client.get("vapid/commitments/5/draw/request?project_id=5")
```

Then comes the question of why it only works for `GET`s and not `POST`s and having to explain that to new users. For V3 I am totally favor in having explicit methods we can call -  its just that in its current shape (V2), its pretty much impossible to guess or logically construct a method because things are so inconsistent. You end up looking at the docs anyway, and its easier to just use the URL instead of trying to figure out what the proper method name should be.

**Comment by philipqnguyen** [comment]
Ah makes sense.
